export default {
  "login": "racharlasrikanth",
  "id": 66104291,
  "node_id": "MDQ6VXNlcjY2MTA0Mjkx",
  "avatar_url": "https://avatars.githubusercontent.com/u/66104291?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/racharlasrikanth",
  "html_url": "https://github.com/racharlasrikanth",
  "followers_url": "https://api.github.com/users/racharlasrikanth/followers",
  "following_url": "https://api.github.com/users/racharlasrikanth/following{/other_user}",
  "gists_url": "https://api.github.com/users/racharlasrikanth/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/racharlasrikanth/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/racharlasrikanth/subscriptions",
  "organizations_url": "https://api.github.com/users/racharlasrikanth/orgs",
  "repos_url": "https://api.github.com/users/racharlasrikanth/repos",
  "events_url": "https://api.github.com/users/racharlasrikanth/events{/privacy}",
  "received_events_url": "https://api.github.com/users/racharlasrikanth/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Srikanth Racharla",
  "company": "@Vellore institute of technology",
  "blog": "https://www.linkedin.com/in/srikanth-racharla-9015041a0/",
  "location": "Hyderabad",
  "email": null,
  "hireable": null,
  "bio": "I am a skilled in AWS with Devops and efficient Web Developer, passionate about solving real life problems. Currently I have been working as a Software Engineer",
  "twitter_username": null,
  "public_repos": 37,
  "public_gists": 0,
  "followers": 10,
  "following": 1,
  "created_at": "2020-05-29T04:01:16Z",
  "updated_at": "2021-12-18T11:36:36Z"
  };